version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: cardgame
      POSTGRES_USER: cardgame
      POSTGRES_PASSWORD: cardgame
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cardgame
      SPRING_DATASOURCE_USERNAME: cardgame
      SPRING_DATASOURCE_PASSWORD: cardgame
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    ports:
      - "8080:8080"
    restart: always

volumes:
  pgdata: