spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cardgame?user=stanislav
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5


  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  validation:
    enabled: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: public
    table: flyway_schema_history
    validate-on-migrate: true
    clean-disabled: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springdoc: DEBUG

app:
  validation:
    game:
      max-players: 4
      target-score: 30
    card:
      min-value: 0
      max-value: 10

jwt:
  secret: "your256bitsecretkeyherethatisatleast64characterslongforsigningthejwttokensecurely12345"
  expiration: 86400000 # 24 hours in milliseconds

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  show-actuator: false
  packages-to-scan: com.example.CardGame

game:
  cards:
    initial-per-player: 5
    points:
      min-value: 1
      max-value: 10
      copies: 4
    actions:
      copies: 4